name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/rectangle_994.png
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/arrow_right_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/star_x2.svg
  - assets/vectors/container_x2.svg
  - assets/images/rectangle_992.png
  - assets/images/rectangle_993.png
  - assets/images/rectangle_994.png
  - assets/images/rectangle_9922.png
  - assets/images/rectangle_9921.jpeg
  - assets/vectors/heart_1_x2.svg
  - assets/vectors/stroke_6_x2.svg
  - assets/vectors/home_x2.svg
  - assets/vectors/stroke_7_x2.svg
  - assets/vectors/heart_x2.svg
  - assets/vectors/profile_x2.svg
  - assets/vectors/star_2_x2.svg
  - assets/vectors/star_1_x2.svg
  - assets/vectors/shape_2_x2.svg
  - assets/vectors/stroke_11_x2.svg
  - assets/vectors/vector_235_x2.svg
  - assets/vectors/swm_icons_duotone_location_1_x2.svg
  - assets/vectors/stroke_1_x2.svg
  - assets/vectors/search_x2.svg
  - assets/vectors/stroke_3_x2.svg
  - assets/vectors/shape_x2.svg
  - assets/images/rectangle_988.jpeg

